#ifndef EXTRACT_ZIP_PASS_FROM_CREDMAN_DEFS_H_
#define EXTRACT_ZIP_PASS_FROM_CREDMAN_DEFS_H_

#define ZIP_PASS_EXTRACTED 1
#define ZIP_PASS_NOT_FOUND 0
#define CREDENTIALS_BUFFER_ERROR -1

#endif 